anchors:
  node_version: &node_version 14.15.4
  node_image: &node_image cimg/node:14.15.4
  node_install: &node_install
    - node/install:
        install-npm: false
        install-yarn: true
        node-version: *node_version
  node_install_packages: &node_install_packages
    - node/install-packages:
        cache-path: ~/project/node_modules
        override-ci-command: yarn install
  restore_cache: &restore_cache
    - restore_cache:
        name: Restore Yarn Package Cache
        keys:
          - yarn-packages-{{ checksum "yarn.lock" }}
  save_cache: &save_cache
    - save_cache:
        name: Save Yarn Package Cache
        key: yarn-packages-{{ checksum "yarn.lock" }}
        paths:
          - ~/.cache/yarn

jobs:
  install:
    docker:
      - image: *node_image
    steps:
      - checkout
      - <<: *node_install
      - <<: *restore_cache
      - <<: *node_install_packages
      - <<: *save_cache
  test:
    docker:
      - image: *node_image
    steps:
      - checkout
      - <<: *node_install
      - <<: *restore_cache
      - <<: *node_install_packages
      - <<: *save_cache
      - run: yarn lint
      - run: yarn test
  generate:
    docker:
      - image: *node_image
    steps:
      - checkout
      - <<: *node_install
      - <<: *restore_cache
      - <<: *node_install_packages
      - run: yarn generate
  deploy:
    docker:
      - image: *node_image
    steps:
      - checkout
      - <<: *node_install
      - <<: *restore_cache
      - <<: *node_install_packages
      - run: yarn generate
      - gcs/gcs-auth
      - gcs/gcs-rsync:
          bucket: "gs://codynog.com"
          source: "/out"

orbs:
  node: circleci/node@4.1.0
  gcs: t3n/gcs@0.1.3
version: 2.1
workflows:
  test_my_app:
    jobs:
      - test
      - generate:
          filters:
            branches:
              ignore:
                - main
      - deploy:
          requires:
            - test
          filters:
            tags:
              only:
                - qa
            branches:
              only:
                - main
